### ISSUE TITLE
costom blocks

### ISSUE THREAD

**Issue by WaseemAlnasser** [allamo123/laravel-grapes#11]
hi mohamed, 
first i want to thank you for the package it is very well done.
i want to ask you if it is possible to make costom blocks, i am making an ecommerce website and i want to make a functionality where i would add a block for example a products block and select multiple products from a dropdown  then it would attach these products to the block and show them in the page .

and thank you again

**Comment by allamo123** [comment]
Hi, @WaseemAlnasser

This feature not supported in this version and the pro version will release soon with this feature.

Thanks

**Comment by WaseemAlnasser** [comment]
Hi, @allamo123
i actually made a dynamic block  and it worked i want to ask i am adding a component to the canves directly 
how can i add style to the added component please help if you can

**Comment by allamo123** [comment]
hi, @WaseemAlnasser ,,,
this need to be done through laravel-grapes.js but the file is minified and this feature will coming soon with Varity options please read the documentation differences btween free version and premium version you will find dynamic laravel shortcode widget in this version it supported only 1 shortcode **laravel auth email merged with guard**

Thanks
