### ISSUE TITLE
how can i add user_id so that user can create there own page and publish it

### ISSUE THREAD

**Issue by zahidsoft** [allamo123/laravel-grapes#12]
actually, I want to create multie auth system in our application. That's why we need to filter pages user-wise. so that Every user can see their own created page, not other created pages.
how can I do it in this package.

**Comment by allamo123** [comment]
**Hello @zahidsof**t 
The package handles multiple auth and multiple guards at one page, for example if you need to show part of the page for specific guard you must defined it @trait settings for the component, please read the documentation related to this part.
At the moment Laravel Grapes not come with this feature but we will take care for this suggestion.

**Thanks @zahidsoft for your suggestion.**
