### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by slagusev** [allamo123/laravel-grapes#13]
Hi!
Where are they located and how to translate the file. to change the interface of the constructor to another language? (block name and so on)

**Comment by allamo123** [comment]
hello @slagusev 

Go to config/lg.php and define your languages in languages array like below
```jsx
<?php

    return [
        // routes configurations
        'builder_prefix' => 'hello', // prefix for builder

        'middleware' => null, // middleware for builder

        'frontend_prefix' => '', // prefix for frontend

        /* Define additional translation languages. */
        'languages' => [
            'ar',
            'es',
        ],
    ];`
```
after that go to your page builder and select the text and select component settings you will find your languages local write your translated text and Laravel Grapes do all the magic for you. 

please read the documentation at page content select translation.
