### ISSUE TITLE
how can i filter template using user wise

### ISSUE THREAD

**Issue by zahidsoft** [allamo123/laravel-grapes#14]
i have multiple users so I want to filter the template user-wise. so that no one can access another user template. 
how can I find the template user-wise?
please help me.

**Comment by allamo123** [comment]
hello @zahidsoft  

This is not for multiple websites its only for one website but we will study to do it in the future.

**Comment by zahidsoft** [comment]
Yes i have one website but multiple user. Who create this page how to checket it. And how to protected the page form other user
