### ISSUE TITLE
Unable to Authenticate by routes/web.php

### ISSUE THREAD

**Issue by rehmanalira** [allamo123/laravel-grapes#17]
Hello 
I am using laravel-grapes. I just have a problem when I have install this I have two web.php on is my own and second is laravel-grapes but the problem I am getting I am unable to authenticate
![image](https://user-images.githubusercontent.com/67744010/229376401-b96398ff-888d-458c-a98c-a91b63f95518.png)
 the routes of laravel-grapes  this is my lg.php but it is not still checking the routes if I add the the autehntication like this 
![image](https://user-images.githubusercontent.com/67744010/229376486-eceec725-a7ce-46a7-93bf-3ae2f8361a2d.png)
it redirect me to login page if I am still login . kindly  provide me that solution

**Comment by allamo123** [comment]
hello @rehmanalira 
please do not change route file, if you need to assign middleware directly you can navigate to `src/LaravelGrapesServiceProvider`
you will find 
` protected function routeBuilderConfiguration()
    {
        return [
            'prefix' => config('lg.builder_prefix'),
            'middleware' => null,
        ];
    }`
you can assign middleware directly
