### ISSUE TITLE
View Not Found On Server Site

### ISSUE THREAD

**Issue by fakrulue** [allamo123/laravel-grapes#18]
hello others view file working well but your package view file not loading in server site. it's working on localhost but problem arrived when it's upload on live server
![Screenshot_2](https://github.com/allamo123/laravel-grapes/assets/119164690/b447cd8d-946d-46b3-98d0-2eed53e66f77)

**Comment by datnguyenthang** [comment]
Change `msa/laravel-grapes/resources/Views` to `msa/laravel-grapes/resources/views`.

**Comment by rafa-lobo** [comment]
> Change `msa/laravel-grapes/resources/Views` to `msa/laravel-grapes/resources/views`.

This worked for me, was having this exact same problem. But of course we shouldn't have to edit this on the vendor folder, any workarounds?
